# Welcome to Jekyll!
#
#
#############################################################################
# This config file is meant for settings that affect your whole blog, values
## 이 환경설정 파일은 당신의 모든 블로그에 영향을 미치고,
# which you are expected to set up once and rarely edit after that. If you find
## 한번 설정을 하면 좀체로 수정하지 않을 것입니다.

# yourself editing this file very often, consider using Jekyll's data files
## 이 파일을 자주 편집할 것이라면
# feature for the data you need to update frequently.
## Jekyll 데이터 파일 기능을 자주 업데이트해야하는 데이터로 사용하는 것이 좋습니다.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
## 기술적인 이유로 이 파일은, 당신이 'bundle exec jekyll serve'를 실행 중일 때 자동적으로 로드해주지 않습니다.
## 따라서 이 파일을 수정하였다면 서버를 재시작해야 합니다.
###############################################################################


# Site settings
#
############################################################################
# These are used to personalize your new site. If you look in the HTML files,
## 이 부분은 당신의 사이트를 개인화 합니다.
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
## HTML 파일을 보면 {{site.title}}, {{site.email}} 등을 통해 액세스 할 수 있습니다.
#
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
## 당신은 {{ site.myvariable }}을 통하여 당신이 정한 맞춤 변수로 템플릿에 접근할 수 있습니다.
#
# 여기를 참조합니다.
# http://jekyllrb-ko.github.io/docs/configuration/
#########################


# Site Settings
#
###############################################################
## 파일 종류별 위치
###source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null
## 읽기 처리방법
safe: False
include: []
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
keep_files: ["_post", ".git"]
encoding: UTF-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
## 컨텐츠 필터링
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

lang: en # _data/i18n.yml.
## 출력 방식
### permalink: /blog/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
### paginate_path: /page:num
### timezone:      null
### quiet:    false
### defaults: []

## Build settings
## 플러그인
whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  style: compressed
### theme: jekyll-theme-simple-texture
### theme: minima
## Conversion
markdown:    kramdown
### highlighter: rouge
### lsi:         false
### excerpt_separator: "\n\n"
### incremental: false
## 마크다운 처리기
markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

## Site Data
###detach:  false
port:    4000
### host:    127.0.0.1
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: 끄적끄적 cODe
description: "python django code ..."
keywords: 'python, django, jekyll, blog'
author:
  name: '주인장'
  job_title:
  location:
  email: 'jskim2code@gmail.com'
  social_links:
    - name: facebook
      url:
    - name: github
      url:  https://github.com/ehfgk78/
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url:
    - name: vk
      url:

home:
  section1: <h1>끄적끄적 cODe</h1>
  section2: <h2>안다고 착각하는 것들도 잊을까 두려워 끄적끄적~~~</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/ehfgk78/" title="https://github.com/ehfgk78/"></a></div>

blog:
  # 저작권 관련
  ## A link to CC License of your choice.
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/
  ## An image of your CC License.
  cc_license_image: /assets/images/theme/cc-by-sa.png
  # 블로그 하단 설명 + About(home)설명
  footer_content: 파이썬을 공부하다가 코딩에 급관심이 생겼습니다. <br> 알거나(?) <strong>알았다고 착각한 것(!!!)들</strong>을 기억의 한계 안으로 끄적입니다. <br> 연락은 위 이모티콘을 눌러보시고 관련 코드는 github에 올려놓았습니다.~

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_analytics: # e.g. 'UA-42456515-5'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/


